"""estado field to vigencia table

Revision ID: 551b3238789e
Revises: e18f45e2b11a
Create Date: 2025-05-14 15:56:39.477471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "551b3238789e"
down_revision: Union[str, None] = "e18f45e2b11a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "actividades",
        sa.Column("producto", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "actividades",
        sa.Column(
            "indicador_producto", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "vigencias",
        sa.Column(
            "estado", sa.Enum("ABIERTO", "HECHO", name="termenum"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vigencias", "estado")
    op.drop_column("actividades", "indicador_producto")
    op.drop_column("actividades", "producto")
    # ### end Alembic commands ###
