"""term migration

Revision ID: 7f264975c9f3
Revises: 
Create Date: 2025-07-07 10:36:28.835140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7f264975c9f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vigencias', sa.Column('nombrevigencia', sqlmodel.sql.sqltypes.AutoString(), server_default='N/A', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vigencias', 'nombrevigencia')
    # ### end Alembic commands ###
